# Generated by Django 5.1.6 on 2025-12-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customer_options_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customer',
            name='patronymic',
            field=models.CharField(blank=True, help_text="Father's name (отчество)", max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('name', 'surname', 'patronymic', 'place')},
        ),
    ]
