# Generated by Django 5.0.6 on 2026-01-01 17:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customer_unique_together_customer_patronymic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['surname', 'name'], 'verbose_name': 'Müştəri', 'verbose_name_plural': 'Müştərilər'},
        ),
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['-date_given', '-created_at'], 'verbose_name': 'Borc', 'verbose_name_plural': 'Borclar'},
        ),
        migrations.AlterModelOptions(
            name='pharmacist',
            options={'ordering': ['name', 'surname'], 'verbose_name': 'Aptekçi', 'verbose_name_plural': 'Aptekçilər'},
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_profile', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='patronymic',
            field=models.CharField(blank=True, help_text='Ata adı (отчество)', max_length=100, null=True, verbose_name='Ata adı'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='place',
            field=models.CharField(default='Unknown', help_text='Müştərinin haradan olduğu', max_length=200, verbose_name='Yer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Məbləğ'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='main.customer', verbose_name='Müştəri'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='date_given',
            field=models.DateField(default=django.utils.timezone.now, help_text='Borcun verildiyi tarix', verbose_name='Verilmə tarixi'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='description',
            field=models.TextField(blank=True, help_text='Borcla bağlı əlavə qeydlər', null=True, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Ödənilib'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ödəniş tarixi'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='pharmacist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='main.pharmacist', verbose_name='Aptekçi'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='promise_date',
            field=models.DateField(help_text='Müştərinin pulu qaytarmaq üçün vəd etdiyi tarix', verbose_name='Vəd tarixi'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-poçt'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Soyad'),
        ),
    ]
