# Generated by Django 5.0.6 on 2026-01-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customer_options_alter_debt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Nağd'), ('card', 'Kart'), ('posterminal', 'Posterminal')], help_text='Ödəniş üsulu', max_length=20, null=True, verbose_name='Ödəniş üsulu'),
        ),
    ]
