# Generated by Django 5.0.6 on 2026-01-01 20:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_debt_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='date_given',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Borcun verildiyi tarix və vaxt', verbose_name='Verilmə tarixi'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='paid_date',
            field=models.DateTimeField(blank=True, help_text='Ödəniş tarixi və vaxtı', null=True, verbose_name='Ödəniş tarixi'),
        ),
    ]
