# Generated by Django 5.0.6 on 2026-01-01 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_debt_date_given_alter_debt_paid_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tələb olunan məbləğ')),
                ('requested_paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Tələb olunan ödəniş tarixi')),
                ('reason', models.TextField(help_text='Dəyişiklik səbəbi', verbose_name='Səbəb')),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('approved', 'Təsdiqlənib'), ('rejected', 'Rədd edilib')], default='pending', max_length=20, verbose_name='Status')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='Baxış qeydləri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Baxılma tarixi')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='main.debt', verbose_name='Borc')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='main.pharmacist', verbose_name='Tələb edən')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_edit_requests', to=settings.AUTH_USER_MODEL, verbose_name='Baxılan')),
            ],
            options={
                'verbose_name': 'Borc redaktə tələbi',
                'verbose_name_plural': 'Borc redaktə tələbləri',
                'ordering': ['-created_at'],
            },
        ),
    ]
