# Generated by Django 5.0.6 on 2026-01-01 22:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_debteditrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Borcun silindiyi tarix və vaxt', null=True, verbose_name='Silinmə tarixi'),
        ),
        migrations.AddField(
            model_name='debt',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_debts', to=settings.AUTH_USER_MODEL, verbose_name='Silən'),
        ),
        migrations.AddField(
            model_name='debt',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Borcun silinib-silinməməsi', verbose_name='Silinib'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Məbləğ')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Ödəniş tarixi və vaxtı', verbose_name='Ödəniş tarixi')),
                ('payment_method', models.CharField(choices=[('cash', 'Nağd'), ('card', 'Kart'), ('posterminal', 'Posterminal')], help_text='Ödəniş üsulu', max_length=20, verbose_name='Ödəniş üsulu')),
                ('notes', models.TextField(blank=True, help_text='Ödənişlə bağlı əlavə qeydlər', null=True, verbose_name='Qeydlər')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Yaradan')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.debt', verbose_name='Borc')),
            ],
            options={
                'verbose_name': 'Ödəniş',
                'verbose_name_plural': 'Ödənişlər',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
