# Generated by Django 5.1.6 on 2026-01-03 14:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_debt_deleted_at_debt_deleted_by_debt_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='pharmacist',
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('surname', models.CharField(max_length=100, verbose_name='Soyad')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-poçt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashier_profile', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Kassir',
                'verbose_name_plural': 'Kassirlər',
                'ordering': ['name', 'surname'],
            },
        ),
        migrations.AddField(
            model_name='debt',
            name='cashier',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='main.cashier', verbose_name='Kassir'),
        ),
        migrations.AlterField(
            model_name='debteditrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='main.cashier', verbose_name='Tələb edən'),
        ),
        migrations.DeleteModel(
            name='Pharmacist',
        ),
    ]
