# Generated by Django 5.1.6 on 2026-01-03 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_debt_pharmacist_cashier_debt_cashier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='main.cashier', verbose_name='Kassir'),
        ),
    ]
